server {
    listen 80;
    root /usr/share/nginx/html;

    location /mas-admin/ {
        try_files $uri $uri/ /mas-admin/index.html;
    }

    location = / {
        return 301 /mas-admin/;
    }
}
